version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
#docker run -tip 1883:1883 -p 9001:9001 pascaldevink/rpi-mosquitto
    image: pascaldevink/rpi-mosquitto:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
      - "1883:1883"
      - "9001:9001"
    networks:
      - webnet
networks:
  webnet:
